import Header from '../../components/Header';
import '../../styles/globals.css';

import { Montserrat, Poppins, BenchNine } from 'next/font/google';
import GetScrollPosition from '../../components/animated/GetScrollPosition';
import Component from '../../components/Component';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
});

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-poppins',
});
const benchnine = BenchNine({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
  variable: '--font-benchnine',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="w-screen overflow-x-hidden" lang="en">
      <body
        className={`bg-[#1B1B1B]  text-white w-screen   ${montserrat.variable} ${poppins.variable} ${benchnine.variable}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
